# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------
# coding: utf-8

from setuptools import setup, find_packages

NAME = "resourcemanagementclient"
VERSION = "2016-09-01"

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["msrest>=0.4.0", "msrestazure>=0.4.0"]

setup(
    name=NAME,
    version=VERSION,
    description="ResourceManagementClient",
    author_email="",
    url="",
    keywords=["Swagger", "ResourceManagementClient"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    Provides operations for working with resources and resource groups.
    """
)
