# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.service_client import ServiceClient
from msrest import Configuration, Serializer, Deserializer
from .version import VERSION
from .operations.greeting_operations import GreetingOperations


class HelloWorldConfiguration(Configuration):
    """Configuration for HelloWorld
    Note that all parameters used to create this instance are saved as instance
    attributes.

    :param str base_url: Service URL
    :param str filepath: Existing config
    """

    def __init__(
            self, base_url=None, filepath=None):

        if not base_url:
            base_url = 'http://swaggersample.azurewebsites.net'

        super(HelloWorldConfiguration, self).__init__(base_url, filepath)

        self.add_user_agent('helloworld/{}'.format(VERSION))


class HelloWorld(object):
    """HelloWorld

    :ivar config: Configuration for client.
    :vartype config: HelloWorldConfiguration

    :ivar greeting: Greeting operations
    :vartype greeting: .operations.GreetingOperations

    :param str base_url: Service URL
    :param str filepath: Existing config
    """

    def __init__(
            self, base_url=None, filepath=None):

        self.config = HelloWorldConfiguration(base_url, filepath)
        self._client = ServiceClient(None, self.config)

        client_models = {}
        self._serialize = Serializer(client_models)
        self._deserialize = Deserializer(client_models)

        self.greeting = GreetingOperations(
            self._client, self.config, self._serialize, self._deserialize)
