# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .deployments_operations import DeploymentsOperations
from .providers_operations import ProvidersOperations
from .resource_groups_operations import ResourceGroupsOperations
from .resources_operations import ResourcesOperations
from .tags_operations import TagsOperations
from .deployment_operations_operations import DeploymentOperationsOperations

__all__ = [
    'DeploymentsOperations',
    'ProvidersOperations',
    'ResourceGroupsOperations',
    'ResourcesOperations',
    'TagsOperations',
    'DeploymentOperationsOperations',
]
