// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Azure.Models
{
    using System.Linq;

    /// <summary>
    /// The deployment export result.
    /// </summary>
    public partial class DeploymentExportResult
    {
        /// <summary>
        /// Initializes a new instance of the DeploymentExportResult class.
        /// </summary>
        public DeploymentExportResult() { }

        /// <summary>
        /// Initializes a new instance of the DeploymentExportResult class.
        /// </summary>
        /// <param name="template">The template content.</param>
        public DeploymentExportResult(object template = default(object))
        {
            Template = template;
        }

        /// <summary>
        /// Gets or sets the template content.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "template")]
        public object Template { get; set; }

    }
}
