// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Azure.Models
{

    /// <summary>
    /// Defines values for DeploymentMode.
    /// </summary>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum DeploymentMode
    {
        [System.Runtime.Serialization.EnumMember(Value = "Incremental")]
        Incremental,
        [System.Runtime.Serialization.EnumMember(Value = "Complete")]
        Complete
    }
}
