// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Azure.Models
{

    /// <summary>
    /// Defines values for ResourceIdentityType.
    /// </summary>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum ResourceIdentityType
    {
        [System.Runtime.Serialization.EnumMember(Value = "SystemAssigned")]
        SystemAssigned
    }
}
