/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the BasicDependency class.
 * @constructor
 * Deployment dependency information.
 *
 * @member {string} [id] The ID of the dependency.
 * 
 * @member {string} [resourceType] The dependency resource type.
 * 
 * @member {string} [resourceName] The dependency resource name.
 * 
 */
function BasicDependency() {
}

/**
 * Defines the metadata of BasicDependency
 *
 * @returns {object} metadata of BasicDependency
 *
 */
BasicDependency.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'BasicDependency',
    type: {
      name: 'Composite',
      className: 'BasicDependency',
      modelProperties: {
        id: {
          required: false,
          serializedName: 'id',
          type: {
            name: 'String'
          }
        },
        resourceType: {
          required: false,
          serializedName: 'resourceType',
          type: {
            name: 'String'
          }
        },
        resourceName: {
          required: false,
          serializedName: 'resourceName',
          type: {
            name: 'String'
          }
        }
      }
    }
  };
};

module.exports = BasicDependency;
