/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the DeploymentExtendedFilter class.
 * @constructor
 * Deployment filter.
 *
 * @member {string} [provisioningState] The provisioning state.
 * 
 */
function DeploymentExtendedFilter() {
}

/**
 * Defines the metadata of DeploymentExtendedFilter
 *
 * @returns {object} metadata of DeploymentExtendedFilter
 *
 */
DeploymentExtendedFilter.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'DeploymentExtendedFilter',
    type: {
      name: 'Composite',
      className: 'DeploymentExtendedFilter',
      modelProperties: {
        provisioningState: {
          required: false,
          serializedName: 'provisioningState',
          type: {
            name: 'String'
          }
        }
      }
    }
  };
};

module.exports = DeploymentExtendedFilter;
