/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the DeploymentExportResult class.
 * @constructor
 * The deployment export result.
 *
 * @member {object} [template] The template content.
 * 
 */
function DeploymentExportResult() {
}

/**
 * Defines the metadata of DeploymentExportResult
 *
 * @returns {object} metadata of DeploymentExportResult
 *
 */
DeploymentExportResult.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'DeploymentExportResult',
    type: {
      name: 'Composite',
      className: 'DeploymentExportResult',
      modelProperties: {
        template: {
          required: false,
          serializedName: 'template',
          type: {
            name: 'Object'
          }
        }
      }
    }
  };
};

module.exports = DeploymentExportResult;
