/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the HttpMessage class.
 * @constructor
 * @member {object} [content] HTTP message content.
 * 
 */
function HttpMessage() {
}

/**
 * Defines the metadata of HttpMessage
 *
 * @returns {object} metadata of HttpMessage
 *
 */
HttpMessage.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'HttpMessage',
    type: {
      name: 'Composite',
      className: 'HttpMessage',
      modelProperties: {
        content: {
          required: false,
          serializedName: 'content',
          type: {
            name: 'Object'
          }
        }
      }
    }
  };
};

module.exports = HttpMessage;
