/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the ParametersLink class.
 * @constructor
 * Entity representing the reference to the deployment paramaters.
 *
 * @member {string} uri The URI of the parameters file.
 * 
 * @member {string} [contentVersion] If included, must match the
 * ContentVersion in the template.
 * 
 */
function ParametersLink() {
}

/**
 * Defines the metadata of ParametersLink
 *
 * @returns {object} metadata of ParametersLink
 *
 */
ParametersLink.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'ParametersLink',
    type: {
      name: 'Composite',
      className: 'ParametersLink',
      modelProperties: {
        uri: {
          required: true,
          serializedName: 'uri',
          type: {
            name: 'String'
          }
        },
        contentVersion: {
          required: false,
          serializedName: 'contentVersion',
          type: {
            name: 'String'
          }
        }
      }
    }
  };
};

module.exports = ParametersLink;
