/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the Plan class.
 * @constructor
 * Plan for the resource.
 *
 * @member {string} [name] The plan ID.
 * 
 * @member {string} [publisher] The publisher ID.
 * 
 * @member {string} [product] The offer ID.
 * 
 * @member {string} [promotionCode] The promotion code.
 * 
 */
function Plan() {
}

/**
 * Defines the metadata of Plan
 *
 * @returns {object} metadata of Plan
 *
 */
Plan.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'Plan',
    type: {
      name: 'Composite',
      className: 'Plan',
      modelProperties: {
        name: {
          required: false,
          serializedName: 'name',
          type: {
            name: 'String'
          }
        },
        publisher: {
          required: false,
          serializedName: 'publisher',
          type: {
            name: 'String'
          }
        },
        product: {
          required: false,
          serializedName: 'product',
          type: {
            name: 'String'
          }
        },
        promotionCode: {
          required: false,
          serializedName: 'promotionCode',
          type: {
            name: 'String'
          }
        }
      }
    }
  };
};

module.exports = Plan;
