/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the ResourceGroupFilter class.
 * @constructor
 * Resource group filter.
 *
 * @member {string} [tagName] The tag name.
 * 
 * @member {string} [tagValue] The tag value.
 * 
 */
function ResourceGroupFilter() {
}

/**
 * Defines the metadata of ResourceGroupFilter
 *
 * @returns {object} metadata of ResourceGroupFilter
 *
 */
ResourceGroupFilter.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'ResourceGroupFilter',
    type: {
      name: 'Composite',
      className: 'ResourceGroupFilter',
      modelProperties: {
        tagName: {
          required: false,
          serializedName: 'tagName',
          type: {
            name: 'String'
          }
        },
        tagValue: {
          required: false,
          serializedName: 'tagValue',
          type: {
            name: 'String'
          }
        }
      }
    }
  };
};

module.exports = ResourceGroupFilter;
