/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

exports.Deployments = require('./deployments');
exports.Providers = require('./providers');
exports.ResourceGroups = require('./resourceGroups');
exports.Resources = require('./resources');
exports.Tags = require('./tags');
exports.DeploymentOperations = require('./deploymentOperations');
