# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DeploymentExtended(Model):
    """Deployment information.

    :param id: The ID of the deployment.
    :type id: str
    :param name: The name of the deployment.
    :type name: str
    :param properties: Deployment properties.
    :type properties: :class:`DeploymentPropertiesExtended
     <Azure.models.DeploymentPropertiesExtended>`
    """ 

    _validation = {
        'name': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'properties': {'key': 'properties', 'type': 'DeploymentPropertiesExtended'},
    }

    def __init__(self, name, id=None, properties=None):
        self.id = id
        self.name = name
        self.properties = properties
