# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Deployment(Model):
    """Deployment operation parameters.

    :param properties: The deployment properties.
    :type properties: :class:`DeploymentProperties
     <Azure.models.DeploymentProperties>`
    """ 

    _attribute_map = {
        'properties': {'key': 'properties', 'type': 'DeploymentProperties'},
    }

    def __init__(self, properties=None):
        self.properties = properties
